apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alist
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources: # FIXME

    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject:

          applicationName: alist

          service:
            enabled: true
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: 5244
              - name: https
                port: 443
                targetPort: 5245
              - name: s3
                port: 9000
                targetPort: 5246
              - name: ftp
                port: 21
                targetPort: 5221
              - name: sftp
                port: 22
                targetPort: 5222

          deployment:
            enabled: true
            name: alist
            replicas: 1
            resources:
              limits:
                cpu: 300m
                memory: 300Mi
              requests:
                cpu: 50m
                memory: 50Mi
            image:
              repository: xhofe/alist
              tag: v3.45.0-aio
            ports:
              - containerPort: 5244
              - containerPort: 5245
              - containerPort: 5246
              - containerPort: 5221
              - containerPort: 5222
            volumeMounts:
              log:
                mountPath: /opt/alist/data/log
              temp:
                mountPath: /opt/alist/data/temp
            envFrom:
              config:
                type: configmap
                name: alist-dotenv
              db:
                type: secret
                name: alist-dotenv
            volumes:
              log:
                emptyDir: {}
              temp:
                emptyDir: {}

          configMap:
            enabled: true
            files:
              dotenv:
                BLEVE_DIR: data/bleve
                CDN: ''
                COMPRESS: 'false'
                CORS_ALLOW_HEADERS_0: '*'
                CORS_ALLOW_METHODS_0: '*'
                CORS_ALLOW_ORIGINS_0: '*'
                DELAYED_START: '0'
                DIST_DIR: ''
                FORCE: 'false'
                FTP_ENABLE: 'true'
                FTP_LISTEN: ':5221'
                LOG_ENABLE: 'true'
                LOG_NAME: data/log/log.log
                MAX_AGE: '28800'
                MAX_BACKUPS: '30'
                MAX_CONNECTIONS: '0'
                MAX_SIZE: '10'
                S3_ENABLE: 'true'
                S3_PORT: '5246'
                S3_SSL: 'false'
                SFTP_ENABLE: 'true'
                SFTP_LISTEN: ':5222'
                SCHEME_ADDRESS: 0.0.0.0
                SCHEME_CERT_FILE: ''
                SCHEME_FORCE_HTTPS: 'false'
                SCHEME_HTTPS_PORT: '-1'
                SCHEME_HTTP_PORT: '5244'
                SCHEME_KEY_FILE: ''
                SCHEME_UNIX_FILE: ''
                SCHEME_UNIX_FILE_PERM: ''
                SITE_URL: ''
                TASKS_COPY_MAX_RETRY: '2'
                TASKS_COPY_WORKERS: '5'
                TASKS_DOWNLOAD_MAX_RETRY: '1'
                TASKS_DOWNLOAD_WORKERS: '5'
                TASKS_TRANSFER_MAX_RETRY: '2'
                TASKS_TRANSFER_WORKERS: '5'
                TASKS_UPLOAD_MAX_RETRY: '0'
                TASKS_UPLOAD_WORKERS: '5'
                TEMP_DIR: data/temp
                TLS_INSECURE_SKIP_VERIFY: 'true'
                TOKEN_EXPIRES_IN: '48'

          secret:
            enabled: true
            files:
              alist-dotenv:
                stringData:
                  # # SQLite
                  # DB_TYPE: sqlite3
                  # DB_FILE: data/data.db

                  # PostgreSQL
                  DB_TYPE: postgres
                  DB_DSN: ''
                  DB_HOST: FIXME-postgres.infra.svc.cluster.local
                  DB_PORT: '5432'
                  DB_SSL_MODE: disable
                  DB_USER: FIXME
                  DB_PASS: FIXME
                  DB_NAME: FIXME
                  DB_TABLE_PREFIX: x_

                  MEILISEARCH_API_KEY: ''
                  MEILISEARCH_HOST: http://localhost:7700
                  MEILISEARCH_INDEX_PREFIX: ''

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:
            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: alist-https
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: alist
                  app.kubernetes.io/component: https
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                hostnames:
                  - FIXME.alist.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - kind: Service
                        namespace: self-hosted
                        name: alist
                        port: 80

            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: alist-s3
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: alist
                  app.kubernetes.io/component: s3
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                hostnames:
                  - FIXME.alist-s3.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - kind: Service
                        namespace: self-hosted
                        name: alist
                        port: 9000

            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: alist-http
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: alist
                  app.kubernetes.io/component: http
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: web
                hostnames:
                  - FIXME.alist.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    filters:
                      - type: RequestRedirect
                        requestRedirect:
                          scheme: https
                          statusCode: 302
