apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baikal-main
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: baikal
    targetRevision: 1.2.5
    helm:
      values: |
        common:
          image:
            tag: 0.10.1-nginx
          deployment:
            cpuLimit: 200m
            cpuRequest: 30m
            memoryLimit: 200Mi
            memoryRequest: 30Mi
          persistence:
            volumes:
              - name: data
                containerMount: /var/www/baikal/Specific
                # pvcClaim: 
                size: 4Gi
                # storageClassName: local-path
              - name: config
                containerMount: /var/www/baikal/config
                # pvcClaim: 
                size: 1Gi
                # storageClassName: local-path
          ingress:
            enabled: false
            # isIngressRoute: false
            # ingressClassName: traefik
            # entrypoint: websecure
            # hostName: baikal.127.0.0.1.sslip.io
            # tls:
            #   enabled: true
            #   certResolver: letsencrypt-issuer
            #   secretName: wildcard-cert
