apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-k8s
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources: # FIXME

    - repoURL: https://cdwv.github.io/bitwarden-k8s/
      chart: bitwarden-k8s
      targetRevision: 0.1.7
      helm:
        valuesObject:

          image:
            repository: vaultwarden/server
          resources:
            limits:
              cpu: 200m
              ram: 200Mi
            requests:
              cpu: 50m
              ram: 50Mi
          env:
            SIGNUPS_ALLOWED: true
            INVITATIONS_ALLOWED: true
            # SERVER_ADMIN_EMAIL
            # DOMAIN
            # YUBICO_CLIENT_ID
            # YUBICO_SECRET_KEY
            # DATA_FOLDER
            # DATABASE_URL
            # ATTACHMENTS_FOLDER
            # ICON_CACHE_FOLDER
            # ROCKET_LIMITS
            # ROCKET_WORKERS
            # SMTP_HOST
            # SMTP_FROM
            # SMTP_PORT
            # SMTP_SSL
            # SMTP_EXPLICIT_TLS
            # SMTP_USERNAME
            # SMTP_PASSWORD
            # SHOW_PASSWORD_HINT
            WEB_VAULT_ENABLED: true
          persistence:
            enabled: false
            accessMode: ReadWriteOnce
            size: 4Gi
            repository: vaultwarden/server
            # storageClass:
            # existingClaim:
