apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devtron-main
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: devtroncd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:

    - repoURL: https://helm.devtron.ai
      chart: devtron-operator
      targetRevision: 0.22.78
