apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devtron-routes
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: devtroncd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests: # FIXME

            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: devtron
                namespace: self-hosted
              spec:
                parentRefs:
                  - kind: Gateway
                    name: traefik-gateway
                    namespace: traefik
                    sectionName: web
                  - kind: Gateway
                    name: traefik-gateway
                    namespace: traefik
                    sectionName: websecure
                hostnames:
                  - FIXME.devtron.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - name: devtron
                        namespace: self-hosted
                        kind: Service
                        port: 80
