apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etesync-main
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:

    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject:

          applicationName: etesync

          service:
            enabled: true
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: 3735

          deployment:
            enabled: true
            name: etesync
            replicas: 1
            resources:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 30m
                memory: 30Mi
            image:
              repository: victorrds/etesync
              tag: 0.14-alpine
            ports:
              - containerPort: 3735
            envFrom:
              etesync:
                type: configmap
                name: etesync-dotenv
            containerSecurityContext:
                readOnlyRootFilesystem: false
                runAsNonRoot: false
            initContainers:
              init-permissions:
                image: busybox
                command: ["sh", "-c", "chmod -R 777 /data"]
                volumeMounts:
                  - mountPath: /data
                    name: etesync-data

          persistence:
            enabled: true
            mountPVC: true
            mountPath: /data
            storageSize: 2Gi
            accessMode: ReadWriteOnce
            storageClass:

          configMap:
            enabled: true
            files:
              dotenv:
                SERVER: http
                AUTO_UPDATE: "true"
                SUPER_EMAIL: admin@admin.admin
                SUPER_USER: admin
                SUPER_PASS: admin
