apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubepi-main
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:

    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject:

          applicationName: kubepi

          service:
            enabled: true
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: 80

          deployment:
            enabled: true
            name: kubepi
            replicas: 1
            resources:
              limits:
                cpu: 300m
                memory: 300Mi
              requests:
                cpu: 50m
                memory: 50Mi
            image:
              repository: 1panel/kubepi
              tag: latest
            ports:
              - containerPort: 80
            containerSecurityContext:
              readOnlyRootFilesystem: true
              runAsNonRoot: false
              privileged: true

          persistence:
            enabled: true
            mountPVC: true
            mountPath: /var/lib/kubepi
            storageSize: 4Gi
            accessMode: ReadWriteOnce
            storageClass:

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:

            - apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: kubepi-user
                namespace: kube-system

            - apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                name: kubepi-user
