apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources: # FIXME

    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject:

          applicationName: matrix

          service:
            enabled: true
            type: ClusterIP
            ports:
              - name: http
                port: 80
                targetPort: 8008

          deployment:
            enabled: true
            name: matrix
            replicas: 1
            resources:
              limits:
                cpu: 300m
                memory: 400Mi
              requests:
                cpu: 50m
                memory: 50Mi
            image:
              repository: ghcr.io/element-hq/synapse
              tag: v1.128.0
            ports:
              - containerPort: 8008
            envFrom:
              config:
                type: configmap
                name: matrix-dotenv

          persistent:
            enabled: true
            # storageClass: local-path
            storageSize: 8Gi
            accessMode: ReadWriteOnce
            mountPVC: true
            mountPath: /data

          configMap:
            enabled: true
            files:
              dotenv:
                SYNAPSE_HTTP_PORT: "8008"
                SYNAPSE_REPORT_STATS: "yes"
                SYNAPSE_SERVER_NAME: "FIXME.matrix.127.0.0.1.sslip.io"

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:
            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: matrix-web
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: matrix
                  app.kubernetes.io/component: web
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: web
                hostnames:
                  - FIXME.matrix.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - kind: Service
                        namespace: self-hosted
                        name: matrix
                        port: 80
