apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stalwart
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject:
          manifests:
            - applicationName: stalwart

              service:
                enabled: true
                type: ClusterIP
                ports:
                  - port: 80
                    targetPort: admin
                    name: admin
                  - port: 25
                    targetPort: 25
                    name: smtp-legacy
                    protocol: TCP
                    appProtocol: smtp
                  - port: 587
                    targetPort: 587
                    name: smtp
                    protocol: TCP
                    appProtocol: smtp
                  - port: 465
                    targetPort: 465
                    name: smtps
                    protocol: TCP
                    appProtocol: smtp
                  - port: 143
                    targetPort: 143
                    name: imap
                    protocol: TCP
                  - port: 993
                    targetPort: 993
                    name: imaps
                    protocol: TCP
                  - port: 110
                    targetPort: 110
                    name: pop3
                    protocol: TCP
                  - port: 995
                    targetPort: 995
                    name: pop3s
                    protocol: TCP

              deployment:
                enabled: true
                name: stalwart
                replicas: 1
                resources:
                  limits:
                    cpu: 250m
                    memory: 400Mi
                  requests:
                    cpu: 50m
                    memory: 50Mi
                image:
                  repository: stalwartlabs/mail-server
                  tag: v0.10.5
                ports:
                  - containerPort: 8080
                    name: admin
                  - containerPort: 443
                    name: admin-tls
                  - containerPort: 25
                    hostPort: 25
                    name: smtp-legacy
                  - containerPort: 587
                    hostPort: 587
                    name: smtp
                  - containerPort: 465
                    hostPort: 465
                    name: smtps
                  - containerPort: 143
                    hostPort: 143
                    name: imap
                  - containerPort: 993
                    hostPort: 993
                    name: imaps
                  - containerPort: 110
                    hostPort: 110
                    name: pop3
                  - containerPort: 995
                    hostPort: 995
                    name: pop3s

              persistence:
                enabled: true
                mountPVC: true
                mountPath: /opt/stalwart-mail
                storageClass: local-path
                accessMode: ReadWriteOnce
                size: 4Gi

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:
            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: stalwart-web
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: stalwart
                  app.kubernetes.io/component: web
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: web
                hostnames:
                  - stalwart.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - kind: Service
                        namespace: self-hosted
                        name: stalwart
                        port: 80
