---
name: pre-create-secrets-with-compose
working_dir: deploy/docker/whoami
ensure_docker_secrets:
  - name: compse-ensure-content
    content: |-
      line1
      line2
      line3
---
name: pre-create-secrets
ensure_docker_secrets:
  - name: ensure-content
    content: |-
      line1
      line2
