version: '3'
run: 'always' # "always" | "once" | "when_changed"
method: 'checksum' # "checksum" | "timestamp" | "none"
interval: '5s'
# set:
# shopt:
silent: false
output: 'interleaved' # "interleaved" | "group" | "prefixed"

dotenv: ['.env', './.env']

includes:
  scoop: {taskfile: './taskfile.d/scoop.yaml', optional: true}
  task: {taskfile: './taskfile.d/task.yaml', optional: true}
  winget: {taskfile: './taskfile.d/winget.yaml', optional: true}

  ls: {taskfile: './taskfile.d/task-ls.yaml', optional: false, aliases: [list, l]}
  ll: {taskfile: './taskfile.d/task-ll.yaml', optional: false, aliases: [list-all, la]}

tasks:

  default:
    cmds:
      - task: ll
