apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests:

          - apiVersion: argoproj.io/v1alpha1
            kind: AppProject
            metadata:
              name: infra
              namespace: argocd
            spec:
              clusterResourceWhitelist:
                - group: "*"
                  kind: "*"
              description: infrastructure depended by apps
              destinations:
                - name: "*"
                  namespace: "*"
                  server: "*"
              sourceRepos:
                - "*"

          - apiVersion: argoproj.io/v1alpha1
            kind: AppProject
            metadata:
              name: self-hosted
              namespace: argocd
            spec:
              clusterResourceWhitelist:
                - group: "*"
                  kind: "*"
              description: self-hosted apps
              destinations:
                - name: "*"
                  namespace: self-hosted
                  server: "*"
              sourceRepos:
                - "*"
