---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.8.28
    helm:
      valuesObject:
        configs:
          cm:
            exec.enabled: true
            kustomize.buildOptions: --enable-helm
          cmp:
            create: true

        controller:
          resources:
            limits:
              cpu: 1000m
              memory: 900Gi
            requests:
              cpu: 50m
              memory: 100Mi
          metrics:
            enabled: true

        dex:
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 20Mi
          metrics:
            enabled: true

        redis:
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          metrics:
            enabled: true

        server:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          metrics:
            enabled: true

        repoServer:
          # resources:
          #   limits:
          #     cpu: 50m
          #     memory: 128Mi
          #   requests:
          #     cpu: 10m
          #     memory: 64Mi
          metrics:
            enabled: true

        applicationSet:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          metrics:
            enabled: true

        notifications:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          metrics:
            enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests:
          - apiVersion: argoproj.io/v1alpha1
            kind: AppProject
            metadata:
              name: infra
              namespace: argocd
            spec:
              clusterResourceWhitelist:
                - group: "*"
                  kind: "*"
              description: infrastructure depended by apps
              destinations:
                - name: "*"
                  namespace: "*"
                  server: "*"
              sourceRepos:
                - "*"

          - apiVersion: argoproj.io/v1alpha1
            kind: AppProject
            metadata:
              name: self-hosted
              namespace: argocd
            spec:
              clusterResourceWhitelist:
                - group: "*"
                  kind: "*"
              description: self-hosted apps
              destinations:
                - name: "*"
                  namespace: self-hosted
                  server: "*"
              sourceRepos:
                - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-routes
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests:
          - apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: argocd
              namespace: argocd
              labels:
                app.kubernetes.io/name: argocd
            spec:
              parentRefs:
                - kind: Gateway
                  namespace: traefik
                  name: traefik-gateway
                  sectionName: websecure
              hostnames:
                - argo-cd.127.0.0.1.sslip.io
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      namespace: argocd
                      name: argocd-server
                      port: 443

          - apiVersion: gateway.networking.k8s.io/v1
            kind: HTTPRoute
            metadata:
              name: argocd-http
              namespace: argocd
              labels:
                app.kubernetes.io/name: argocd
            spec:
              parentRefs:
                - kind: Gateway
                  namespace: traefik
                  name: traefik-gateway
                  sectionName: web
              hostnames:
                - argo-cd.127.0.0.1.sslip.io
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  filters:
                    - type: RequestRedirect
                      requestRedirect:
                        scheme: https
                        port: 443
                        statusCode: 301
