apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-main
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 7.8.28
    helm:
      valuesObject:

        configs:
          cm:
            exec.enabled: true
            kustomize.buildOptions: --enable-helm
          cmp:
            create: true

        controller:
          resources:
            limits:
              cpu: 1000m
              memory: 900Gi
            requests:
              cpu: 50m
              memory: 100Mi
          metrics:
            enabled: true

        dex:
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 20Mi
          metrics:
            enabled: true

        redis:
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          metrics:
            enabled: true

        server:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          metrics:
            enabled: true

        repoServer:
          # resources:
          #   limits:
          #     cpu: 50m
          #     memory: 128Mi
          #   requests:
          #     cpu: 10m
          #     memory: 64Mi
          metrics:
            enabled: true

        applicationSet:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          metrics:
            enabled: true

        notifications:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          metrics:
            enabled: true
