apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.15.3
    helm:
      valuesObject:
        crds:
          enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-ci
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory # Debug ONLY without quota
    email: abc@example.com
    privateKeySecretRef:
      name: letsencrypt-ci-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: dns01-cluster-apitoken
              key: api-token
---
apiVersion: v1
kind: Secret
metadata:
  name: dns01-cluster-apitoken
  namespace: cert-manager
type: Opaque
data:
  api-token: xxxxxxx
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory # Debug ONLY without quota
    email: abc@example.com
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: dns01-infra-apitoken
              key: api-token
---
apiVersion: v1
kind: Secret
metadata:
  name: dns01-infra-apitoken
  namespace: infra
type: Opaque
data:
  api-token: xxxxxxx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-wildcard-cert
  namespace: infra
spec:
  issuerRef:
    kind: Issuer
    name: letsencrypt-issuer
  dnsNames:
    - foo.example.com
    - example.com
    - "*.example.com"
  renewBefore: 1440h
  secretName: wildcard-cert
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 256
