apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests: # FIXME

          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-ci
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                # server: https://acme-staging-v02.api.letsencrypt.org/directory # Debug ONLY without quota
                email: FIXME@fixme.com
                privateKeySecretRef:
                  name: letsencrypt-ci-account-key
                solvers:
                  - dns01:
                      cloudflare:
                        apiTokenSecretRef:
                          name: dns01-cluster-apitoken
                          key: api-token

          - apiVersion: v1
            kind: Secret
            metadata:
              name: dns01-cluster-apitoken
              namespace: cert-manager
            stringData:
              api-token: FIXME

          - apiVersion: cert-manager.io/v1
            kind: Issuer
            metadata:
              name: letsencrypt-issuer
              namespace: infra
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                # server: https://acme-staging-v02.api.letsencrypt.org/directory # Debug ONLY without quota
                email: FIXME@fixme.com
                privateKeySecretRef:
                  name: letsencrypt-account-key
                solvers:
                  - dns01:
                      cloudflare:
                        apiTokenSecretRef:
                          name: dns01-infra-apitoken
                          key: api-token

          - apiVersion: v1
            kind: Secret
            metadata:
              name: dns01-infra-apitoken
              namespace: infra
            stringData:
              api-token: FIXME
