apiVersion: 
kind: Application
metadata:
  name: csi-s3
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-s3
  source:
    repoURL: https://yandex-cloud.github.io/k8s-csi-s3/charts
    chart: csi-s3
    targetRevision: 0.41.1
    helm:
      valuesObject:
        secret:
          endpoint: https://s3.example.com
          region: ""
          accessKey: foo
          secretKey: bar

        storageClass:
          create: true
          singleBucket: 
          reclaimPolicy: Retain
          mountOptions: >-
            --memory-limit 1000
            --dir-mode 0777
            --file-mode 0666
            --no-systemd
            --enable-mtime
            --enable-perms
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
