apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-s3-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: csi-s3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://yandex-cloud.github.io/k8s-csi-s3/charts
    chart: csi-s3
    targetRevision: 0.41.1
    helm:
      valuesObject:

        secret:
          create: false
          # endpoint: https://FIXME.com
          # region: ""
          # accessKey: FIXME
          # secretKey: FIXME

        storageClass:
          create: false
          # singleBucket: FIXME
          reclaimPolicy: Retain
          mountOptions: >-
            --memory-limit 1000
            --dir-mode 0777
            --file-mode 0666
            --no-systemd
          # --enable-mtime
          # --enable-perms
