apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juicefs-csi-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://juicedata.github.io/charts/
    chart: juicefs-csi-driver
    targetRevision: 0.21.0
    helm:
      valuesObject:

        metrics:
          enabled: true

        controller:
          replicas: 1

          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 200Mi

        globalConfig:
          mountPodPatch:
            - kk

        kubeletDir: /var/lib/kubelet
        jfsMountDir: /home/juicefs/volume
        jfsConfigDir: /home/juicefs/config
        # jfsMountDir: /var/lib/juicefs/volume
        # jfsConfigDir: /var/lib/juicefs/config
