---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-raw-example
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    # https://github.com/d4nnyx/helm-raw
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: helm-raw-cm
              namespace: playground
            data: {}
          - apiVersion: v1
            kind: Secret
            metadata:
              name: helm-raw-secret
              namespace: playground
            data: {}
        commonAnnotations: {}
        commonLabels: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raw-example
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    # https://github.com/lablabs/raw
    repoURL: https://lablabs.github.io/raw/
    chart: raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: raw-cm
              namespace: playground
            data: {}
          - apiVersion: v1
            kind: Secret
            metadata:
              name: raw-secret
              namespace: playground
            data: {}
        templates: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-example
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: playground
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    # https://github.com/stakater/application
    repoURL: https://stakater.github.io/stakater-charts
    chart: application
    targetRevision: 6.0.2
    helm:
      valuesObject:
        applicationName: prefix
        deployment:
          enabled: false
        service:
          enabled: false

        configMap:
          enabled: true
          additionalLabels:
          annotations:
          files:
            stakater-example-cm:
              k: v
              k2: v2
