apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.15.4
    helm:
      valuesObject:

        csi:
          provisionerReplicas: 1

          # enableCSIEncryption: false

        resources:
          requests:
            cpu: 100m
            memory: 100Mi
