apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-rg
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests:

          - apiVersion: gateway.networking.k8s.io/v1beta1
            kind: ReferenceGrant
            metadata:
              namespace: infra
              name: gateway-cert-rg
            spec:
              from:
                - group: gateway.networking.k8s.io
                  kind: Gateway
                  namespace: traefik
              to:
                - group: ""
                  kind: Secret
