apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-backups
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests: # FIXME

          - apiVersion: velero.io/v1
            kind: Schedule
            metadata:
              name: daily-all-to-r2
              namespace: velero
            spec:
              template:
                includedNamespaces:
                  - "*"
                defaultVolumesToFsBackup: true
                storageLocation: r2
                ttl: 720h0m0s
              schedule: "0 5 * * *"
