apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: action-runner-controller
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set-controller
    targetRevision: 0.12.0
    helm:
      valuesObject: {} # FIXME
