apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anteon-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: anteon
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://getanteon.github.io/anteon-helm-charts/
    chart: anteon
    targetRevision: 2.6.4
    helm:
      valuesObject: {} # FIXME
