apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://runatlantis.github.io/helm-charts
    chart: atlantis
    targetRevision: 5.17.2
    helm:
      valuesObject: {} # FIXME
