apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.15.3
    helm:
      valuesObject:

        crds:
          enabled: true
