apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://chartmuseum.github.io/charts
    chart: chartmuseum
    targetRevision: 3.10.4
    helm:
      valuesObject: {} # FIXME
