apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-sql
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests: # FIXME

            - apiVersion: v1
              kind: Secret
              metadata:
                name: mssql-provider-conn
              type: Opaque
              stringData:
                endpoint: FIXME.com
                port: FIXME
                username: FIXME
                password: FIXME

            - apiVersion: mssql.sql.crossplane.io/v1alpha1
              kind: ProviderConfig
              metadata:
                name: default
              spec:
                credentials:
                  source: MSSQLConnectionSecret
                  connectionSecretRef:
                    namespace: crossplane-system
                    name: mssql-provider-conn
