apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.18.1
    helm:
      valuesObject: {}
