apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flagger-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://flagger.app
    chart: flagger
    targetRevision: 1.41.0
    helm:
      valuesObject: # FIXME

        crd:
          create: true
