apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juicefs-csi-sc
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests: # FIXME

            - apiVersion: v1
              kind: Secret
              metadata:
                name: juicefs-secret
                labels:
                  juicefs.com/validate-secret: "true" # enbale auth info validation
              type: Opaque
              stringData:
                storage: s3 # s3, gcs, oss, cos
                metaurl: https://FIXME
                # token: FIXME-JUICEFS_TOKEN # if you use JuiceFS cloud service
                access-key: FIXME
                secret-key: FIXME
                bucket: FIXME
                name: FIXME-JUICEFS_NAME
                # env: "{TZ: Asia/Tokyo}" # default is UTC
                # format-options: "trash-days=1,block-size=4096" # `juicefs format` options

            - apiVersion: storage.k8s.io/v1
              kind: StorageClass
              metadata:
                name: juicefs
              reclaimPolicy: Delete
              volumeBindingMode: Immediate
              # allowVolumeExpansion: true # true to allow PVC expansion
              provisioner: csi.juicefs.com
              mountOptions: # `juicefs mount` options
                # - FIXME
                # - debug
                # - cache-size=2048
              parameters:
                csi.storage.k8s.io/node-publish-secret-namespace: infra
                csi.storage.k8s.io/node-publish-secret-name: juicefs-secret
                csi.storage.k8s.io/provisioner-secret-namespace: infra
                csi.storage.k8s.io/provisioner-secret-name: juicefs-secret
                # csi.storage.k8s.io/controller-expand-secret-namespace: infra
                # csi.storage.k8s.io/controller-expand-secret-name: juicefs-secret
