apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.17.2
    helm:
      valuesObject: {} # FIXME
