apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewall-routes
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewall-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests: # FIXME

            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: kubewall-web
                namespace: kube-system
                labels:
                  app.kubernetes.io/name: kubewall
                  app.kubernetes.io/component: web
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: web
                hostnames:
                  - kubewall.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - kind: Service
                        namespace: kube-system
                        name: kubewall
                        port: 80

            - apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: kubewall-user
                namespace: kube-system

            - apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                name: kubewall-user
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cluster-admin
              subjects:
                - kind: ServiceAccount
                  name: kubewall-user
                  namespace: kube-system
