apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewall-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewall-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:

    - repoURL: https://github.com/kubewall/kubewall
      path: charts/kubewall
      targetRevision: HEAD
      helm:
        valuesObject: {}

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:

            - apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: kubewall-user
                namespace: kube-system

            - apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                name: kubewall-user
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cluster-admin
              subjects:
                - kind: ServiceAccount
                  name: kubewall-user
                  namespace: kube-system
