apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.30
    path: deploy/chart/local-path-provisioner
    helm:
      values: |-
        nodePathMap:
        - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
          paths:
          - /home/rancher/k3s/storage
        storageClass:
          defaultClass: false
          defaultVolumeType: local
          name: local-path
          reclaimPolicy: Delete
