apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nuclio
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: nuclio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources: # FIXME

    - repoURL: https://nuclio.github.io/nuclio/charts
      chart: nuclio
      targetRevision: 0.20.8
      helm:
        valuesObject:

          registry:
            secretName: FIXME
            pushPullUrl: FIXME
