apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://openebs.github.io/openebs
    chart: openebs
    targetRevision: 4.1.1
    helm:
      valuesObject:

        engines:
          replicated:
            mayastor:
              enabled: false

        hostpathClass:
          basePath: /home/openebs/local
