apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: openfaas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://openfaas.github.io/faas-netes/
    chart: openfaas
    targetRevision: 14.2.105
    helm:
      valuesObject: {} # FIXME
