apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgautoupgrade-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject: # FIXME

          applicationName: pgautoupgrade

          service:
            enabled: true
            type: ClusterIP
            ports:
              - name: postgres
                port: 5432
                targetPort: 5432

          initContainers:
            oneshot-upgrade:
              replicas: 1
              resources:
                limits:
                  cpu: 1000m
                  memory: 1500Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
              image: pgautoupgrade/pgautoupgrade:15-alpine
              envFrom:
                pg-config:
                  type: configmap
                  name: pgautoupgrade-config-dotenv
                pg-secret:
                  type: secret
                  name: pgautoupgrade-secret-dotenv
              env:
                PGAUTO_ONESHOT:
                  value: 'yes'

          deployment:
            enabled: true
            name: pgautoupgrade
            replicas: 1
            resources:
              limits:
                cpu: 1000m
                memory: 1500Mi
              requests:
                cpu: 50m
                memory: 50Mi
            image:
              repository: pgautoupgrade/pgautoupgrade
              tag: 15-alpine
            ports:
              - containerPort: 5432
            envFrom:
              pg-config:
                type: configmap
                name: pgautoupgrade-config-dotenv
              pg-secret:
                type: secret
                name: pgautoupgrade-secret-dotenv
            env:
              PGAUTO_ONESHOT:
                value: 'no' # "yes" to oneshot migrate job; "no" to pg daemon

          configMap:
            enabled: true
            files:
              pgautoupgrade-config-dotenv:
                POSTGRES_PORT: '5432'

          secret:
            enabled: true
            files:
              pgautoupgrade-secret-dotenv:
                stringData:
                  POSTGRES_USER: FIXME
                  POSTGRES_PASSWORD: FIXME

          psersistence:
            enabled: true
            mountPVC: true
            mountPath: /var/lib/postgresql/data
            # name: pgautoupgrade-data
            accessMode: ReadWriteOnce
            storageClass:
            storageSize: 16Gi
