apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.6.0
    helm:
      valuesObject: {} # FIXME
