apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rainbond-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: rbd-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://openchart.goodrain.com/goodrain/rainbond
    chart: rainbond-cluster
    targetRevision: 5.17.3
    helm:
      valuesObject:

        useK3sContainerd: true
