apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader-main
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 2.1.4
    helm:
      valuesObject:

        reloader:
          autoReloadAll: false
          reloadOnCreate: false
          reloadOnDelete: false
          syncAfterRestart: false
          ignoreSecrets: false
          ignoreConfigMaps: false
          isArgoRollouts: false
          isOpenshift: false
          deployment:
            resources:
              limits:
                cpu: 200m
                ram: 200Mi
              requests:
                cpu: 50m
                ram: 50Mi
