apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-prod
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources: # FIXME

    - repoURL: https://charts.loft.sh
      chart: vcluster
      targetRevision: 0.26.0
      helm:
        valuesObject:

          exportKubeConfig:
            context: prod-cluster

          controlPlane:
            backingStore:
              etcd:
                deploy:
                  enabled: true
                  statefulSet:
                    persistence:
                      volumeClaim:
                        enabled: true
                        retentionPolicy: Retain
                        size: 5Gi
                        # storageClass: ''
                        accessModes: ['ReadWriteOnce']

          sync:
            fromHost:
              customResources:
                FIXME.crdname.example.com: {enabled: true, scope: FIXME-namespace}
            toHost:
              customResources:
                FIXME.crdname.example.com: {enabled: true, scope: FIXME-namespace}
