apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-bsl
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://d4nnyx.github.io/helm-raw/
    chart: helm-raw
    targetRevision: 0.1.0
    helm:
      valuesObject:
        manifests: # FIXME

          - apiVersion: velero.io/v1
            kind: BackupStorageLocation
            metadata:
              name: r2
              namespace: velero
            spec:
              default: true
              provider: aws
              config:
                s3Url: https://FIXME.r2.cloudflarestorage.com
                s3ForcePathStyle: "true"
                region: us-east-1
                checksumAlgorithm: "" # To support Cloudflare R2
              credential:
                key: r2
                name: velero-location-credentials
              objectStorage:
                bucket: FIXME

          - apiVersion: velero.io/v1
            kind: BackupStorageLocation
            metadata:
              name: c2
              namespace: velero
            spec:
              provider: aws
              config:
                s3Url: https://FIXME.s3.synologyc2.net
                s3ForcePathStyle: "true"
                region: us-east-1
                checksumAlgorithm: ""
              credential:
                key: c2
                name: velero-location-credentials
              objectStorage:
                bucket: FIXME

          - apiVersion: velero.io/v1
            kind: BackupStorageLocation
            metadata:
              name: e2
              namespace: velero
            spec:
              provider: aws
              config:
                s3Url: https://FIXME.com
                s3ForcePathStyle: "true"
                region: us-east-1
                checksumAlgorithm: ""
              credential:
                key: e2
                name: velero-location-credentials
              objectStorage:
                bucket: FIXME

          - apiVersion: velero.io/v1
            kind: BackupStorageLocation
            metadata:
              name: b2
              namespace: velero
            spec:
              provider: aws
              config:
                s3Url: http://s3.FIXME.backblazeb2.com
                s3ForcePathStyle: "true"
                region: us-east-1
                checksumAlgorithm: ""
              credential:
                key: b2
                name: velero-location-credentials
              objectStorage:
                bucket: FIXME

          - apiVersion: v1
            kind: Secret
            metadata:
              name: velero-location-credentials
              namespace: velero
            stringData:
              b2: |
                [default]
                aws_access_key_id=FIXME
                aws_secret_access_key=FIXME
              c2: |
                [default]
                aws_access_key_id=FIXME
                aws_secret_access_key=FIXME
              e2: |
                [default]
                aws_access_key_id=FIXME
                aws_secret_access_key=FIXME
              r2: |
                [default]
                aws_access_key_id=FIXME
                aws_secret_access_key=FIXME
