services:
  ensure-network:
    image: ${IMAGE_NAME:-docker}:${IMAGE_VERSION:-28-cli}
    command:
      - sh
      - -c
      - |
        docker network inspect ${NETWORK_NAME:-traefik-public} >/dev/null 2>&1 || docker network create --driver ${NETWORK_DRIVER:-overlay} --attachable ${NETWORK_NAME:-traefik-public}
        exec tail -f /dev/null
    environment:
      DOCKER_HOST: unix://${DOCKER_SOCKET:-/var/run/docker.sock}
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
