configs:
  config:
    name: ${CONFIG_NAME}
    environment: ${CONFIG_ENV_VAR:-CONFIG_CONTENT}

services:
  pause:
    image: ${IMAGE_NAME:-k8s.gcr.io/pause}:${IMAGE_VERSION:-3.9}
    configs:
      - config
