secrets:
  secret:
    name: ${SECRET_NAME}
    environment: ${SECRET_ENV_VAR:-SECRET_CONTENT}

services:
  pause:
    image: ${IMAGE_NAME:-k8s.gcr.io/pause}:${IMAGE_VERSION:-3.9}
    secrets:
      - secret
