apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: affine
  namespace: argocd
spec:
  project: self-hosted
  source:
    repoURL: https://openchart.goodrain.com/goodrain/affine
    chart: affine-cluster
    targetRevision: 5.17.3
    helm:
      valuesObject:
        useK3sContainerd: true
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
