apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alist
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: stakater/application
      targetRevision: 6.0.2
      helm:
        valuesObject:
          manifests:
            - applicationName: alist

              service:
                enabled: true
                type: ClusterIP
                ports:
                  - name: web
                    port: 80
                    targetPort: 5244
                  - name: s3
                    port: 9000
                    targetPort: 5246
                  - name: ftp
                    port: 21
                    targetPort: 5221
                  - name: sftp
                    port: 22
                    targetPort: 5222

              deployment:
                enabled: true
                name: alist
                replicas: 1
                resources:
                  limits:
                    cpu: 300m
                    memory: 300Mi
                  requests:
                    cpu: 50m
                    memory: 50Mi
                image:
                  repository: xhofe/alist
                  tag: v3.42.0-aio
                  # pullPolicy: IfNotPresent
                ports:
                  - containerPort: 5244
                  - containerPort: 5246
                  - containerPort: 5221
                  - containerPort: 5222
                volumeMounts:
                  log:
                    mountPath: /opt/alist/data/log
                  temp:
                    mountPath: /opt/alist/data/temp
                envFrom:
                  config:
                    type: configmap
                    name: alist-config-dotenv
                  db:
                    type: secret
                    name: alist-db-dotenv
                volumes:
                  log:
                    emptyDir: {}
                  temp:
                    emptyDir: {}
    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:
            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: alist-web
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: alist
                  app.kubernetes.io/component: web
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                hostnames:
                  - alist.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - kind: Service
                        namespace: self-hosted
                        name: alist
                        port: 80

            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: alist-s3
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: alist
                  app.kubernetes.io/component: s3
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                hostnames:
                  - alist.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - name: alist
                        namespace: self-hosted
                        kind: Service
                        port: 9000

            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: alist-http
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: alist
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: web
                hostnames:
                  - alist.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    filters:
                      - type: RequestRedirect
                        requestRedirect:
                          scheme: https
                          statusCode: 302
