apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alist-web
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: alist
    app.kubernetes.io/component: web
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: traefik
      name: traefik-gateway
      sectionName: websecure
  # TODO: FIXME
  hostnames:
    - alist.xxxxxxx.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: alist
          namespace: self-hosted
          kind: Service
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alist-s3
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: alist
    app.kubernetes.io/component: s3
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: traefik
      name: traefik-gateway
      sectionName: websecure
  # TODO: FIXME
  hostnames:
    - alist-s3.xxxxxxx.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: alist
          namespace: self-hosted
          kind: Service
          port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alist-http
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: alist
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: traefik
      name: traefik-gateway
      sectionName: web
  hostnames:
    - alist.xxxxxxx.com
    - alist-s3.xxxxxxx.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: v1
kind: Service
metadata:
  name: alist
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: alist
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 5244
    - name: s3
      port: 9000
      targetPort: 5246
  selector:
    app.kubernetes.io/name: alist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alist
  namespace: self-hosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alist
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alist
    spec:
      containers:
        - name: alist
          image: xhofe/alist-aria2:v3.41.0
          ports:
            - containerPort: 5244
            - containerPort: 5246
          volumeMounts:
            - name: log
              mountPath: /opt/alist/data/log
            - name: temp
              mountPath: /opt/alist/data/temp
          envFrom:
            - configMapRef:
                name: alist-config-dotenv
            - secretRef:
                name: alist-db-dotenv
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: log
          emptyDir: {}
        - name: temp
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
