apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: apitable
  namespace: self-hosted
spec:
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: web
    - kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  # TODO: FIXME
  hostnames:
    - apitable.xxxxxxx.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: apitable
          namespace: self-hosted
          kind: Service
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apitable
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: apitable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apitable
  ports:
    - port: 80
      targetPort: web
      name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apitable
  namespace: self-hosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apitable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apitable
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: apitable-data
      containers:
        - name: apitable
          image: apitable/all-in-one:latest
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: data
              mountPath: /apitable
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 50Mi
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apitable-data
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
