apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apitable
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    -
      repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject:
          manifests:
            - applicationName: apitable

              service:
                enabled: true
                type: ClusterIP
                ports:
                  -
                    name: web
                    port: 80
                    targetPort: 80

              deployment:
                enabled: true
                name: apitable
                replicas: 1
                resources:
                  limits:
                    cpu: 500m
                    memory: 500Mi
                  requests:
                    cpu: 50m
                    memory: 50Mi
                image:
                  repository: apitable/all-in-one
                  tag: latest
                ports:
                  - containerPort: 80

              persistence:
                enabled: true
                mountPVC: true
                storageSize: 5Gi
                accessMode: ReadWriteOnce

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:
            -
              apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: apitable
                namespace: self-hosted
              spec:
                parentRefs:
                  - kind: Gateway
                    name: traefik-gateway
                    namespace: traefik
                    sectionName: web
                  - kind: Gateway
                    name: traefik-gateway
                    namespace: traefik
                    sectionName: websecure
                hostnames:
                  - apitable.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - name: apitable
                        namespace: self-hosted
                        kind: Service
                        port: 80
