apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.0.2
      helm:
        valuesObject:
          applicationName: bitwarden

          service:
            enabled: true
            type: ClusterIP
            ports:
              - name: web
                port: 80
                targetPort: 80

          deployment:
            enabled: true
            name: bitwarden
            replicas: 1
            resources:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 50m
                memory: 50Mi
            image:
              repository: vaultwarden/server
              tag: 1.33.2-alpine
            ports:
              - containerPort: 80

          persistence:
            enabled: true
            mountPVC: true
            mountPath: /data
            storageSize: 1Gi
            accessMode: ReadWriteMany
            storageClass: csi-s3

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:
            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: bitwarden
                namespace: self-hosted
              spec:
                parentRefs:
                  - kind: Gateway
                    name: traefik-gateway
                    namespace: traefik
                    sectionName: web
                  - kind: Gateway
                    name: traefik-gateway
                    namespace: traefik
                    sectionName: websecure
                hostnames:
                  - bitwarden.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - name: bitwarden
                        namespace: self-hosted
                        kind: Service
                        port: 80
