apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bitwarden
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: bitwarden
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: traefik
      name: traefik-gateway
      sectionName: websecure
  # TODO: FIXME
  hostnames:
    - bitwarden.xxxxxxxxxxxxx.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: bitwarden
          namespace: self-hosted
          kind: Service
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bitwarden-http
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: bitwarden
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: traefik
      name: traefik-gateway
      sectionName: web
  # TODO: FIXME
  hostnames:
    - bitwarden.xxxxxxxxxxxxx.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: v1
kind: Service
metadata:
  name: bitwarden
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: bitwarden
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: bitwarden
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitwarden
  namespace: self-hosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitwarden
    spec:
      containers:
        - name: bitwarden
          image: vaultwarden/server:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bitwarden-pvc
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvc
  namespace: self-hosted
spec:
  storageClassName: csi-s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
