apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: self-hosted
  destination:
    server: https://kubernetes.default.svc
    namespace: self-hosted
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: stakater/application
      targetRevision: 6.0.2
      helm:
        valuesObject:
          manifests:
            - applicationName: gitea

              service:
                enabled: true
                type: ClusterIP
                ports:
                  - name: web
                    port: 80
                    targetPort: 3000

              deployment:
                enabled: true
                name: gitea
                replicas: 1
                resources:
                  limits:
                    cpu: 300m
                    memory: 200Mi
                  requests:
                    cpu: 50m
                    memory: 50Mi
                image:
                  repository: gitea/gitea
                  tag: 1.23
                ports:
                  - containerPort: 3000

              persistence:
                enabled: true
                mountPVC: true
                mountPath: /data
                storageClass: local-path
                accessMode: ReadWriteOnce
                size: 20Gi

    - repoURL: https://d4nnyx.github.io/helm-raw/
      chart: helm-raw
      targetRevision: 0.1.0
      helm:
        valuesObject:
          manifests:
            - apiVersion: gateway.networking.k8s.io/v1
              kind: HTTPRoute
              metadata:
                name: gitea-web
                namespace: self-hosted
                labels:
                  app.kubernetes.io/name: gitea
                  app.kubernetes.io/component: web
              spec:
                parentRefs:
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: websecure
                  - group: gateway.networking.k8s.io
                    kind: Gateway
                    namespace: traefik
                    name: traefik-gateway
                    sectionName: web
                hostnames:
                  - gitea.127.0.0.1.sslip.io
                rules:
                  - matches:
                      - path:
                          type: PathPrefix
                          value: /
                    backendRefs:
                      - kind: Service
                        namespace: self-hosted
                        name: gitea
                        port: 80
