apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubepi
  namespace: self-hosted
spec:
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: web
    - kind: Gateway
      name: traefik-gateway
      namespace: traefik
      sectionName: websecure
  # TODO: FIXME
  hostnames:
    - kubepi.xxxxxxxxx.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kubepi
          namespace: self-hosted
          kind: Service
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kubepi
  namespace: self-hosted
  labels:
    app.kubernetes.io/name: kubepi
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubepi
  ports:
    - port: 80
      targetPort: 80
      name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepi
  namespace: self-hosted
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubepi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubepi
    spec:
      containers:
        - name: kubepi
          image: 1panel/kubepi
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 250m
              memory: 300Mi
            requests:
              cpu: 50m
              memory: 50Mi
      nodeSelector:
        kubernetes.io/os: linux
