name: Backup
on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aldoborrero/use-nix-action@v5
      - name: Use devenv cache from cachix
        uses: cachix/cachix-action@v14
        with:
            name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: nix profile install nixpkgs#go-task
      - run: nix profile install nixpkgs#kopia
      - uses: AnimMouse/setup-restic@v1
      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - run: restic check
        env:
          RESTIC_REPOSITORY: ${{ secrets.RESTIC_REPOSITORY }}
          RESTIC_PASSWORD: ${{ secrets.RESTIC_PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
          B2_ACCOUNT_KEY: ${{ secrets.B2_ACCOUNT_KEY }}
